name: Build Toolkit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependences
        run: |
          sudo apt update
          sudo apt install -y build-essential libpng-dev zlib1g-dev

      - name: Permissions
        run: chmod +x build.sh

      - name: Compile
        run: |
          ./build.sh

      #- name: Show errors
        #if: failure()
        #run: |
          #grep -n -B5 -A5 "error:" build.log || true
          #grep -n -B5 -A5 "undefined" build.log || true
          #tail -100 build.log

      - name: Check output
        run: ls -la

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: RyououGakuenToolkit-Linux
          path: |
            RGT_RGO_Patch_Builder
            RGOFontExtractor
            RGOScriptExtractor
            CPKExtractor
            RGOImageExtractor
            NIMImageExtractor
            ImageColorReducer
            RGOFontGenerator
            ScriptMerger
