name: Build Toolkit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependences
        run: |
          sudo apt update
          sudo apt install -y build-essential libpng-dev zlib1g-dev

      - name: Permissions
        run: chmod +x build.sh

      - name: Compile
        run: ./build.sh

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: RyououGakuenToolkit-Linux
          path: |
            RGT*
            RGO*
            CPK*
            Script*
            Image*
            Auto*
