name: Patch ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependences
        run: |
          sudo apt update
          sudo apt install -y clang libpng-dev zlib1g-dev unzip

      - name: Permissions
        run: chmod +x build.sh

      - name: Compile
        run: ./build.sh
        
      #- name: Check output
      #  run: ls -la
        
      - name: Download RGO assets
        run: |
            python3 -m pip install gdown
            gdown "https://drive.google.com/file/d/1m1FXKe1tMIFy3WQSg8AIHQo3nGQALBdF" -O rgo-assets.zip
            unzip rgo-assets.zip
      - name: Check assets
        run: |
            find assets -maxdepth 3 -type f

      - name: Debug resources
        run: |
            find resources -maxdepth 4 -type f | head -50
            ls -lh assets/cpk/union.cpk
            md5sum assets/cpk/union.cpk
    
      - name: Patch the ISO
        run: |
         chmod +x ./RGT_RGO_Patch_Builder
         chmod +x ./umd-replace-linux-x86_64
         ls -la RGT_RGO_Patch_Builder umd-replace-linux-x86_64
         ./RGT_RGO_Patch_Builder
         
      - name: Upload the Patched ISO
        uses: actions/upload-artifact@v4
        with:
        
            name: Patched ISO
            path: |
              results/RGT_RGO_Patch_Builder/rgopsp.iso
